language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: G8YoiK3aJwv+BbsBlUzDrvOBUkGJ2YcPqYk6xEdvbiGHIHf2dCUWN/yBgd586AeSmH2ac6Eslcvom//TfVjLA8Xx88xyaj3fVWeldNSvv922CJEyszMlxyyfA63o6HIkhvYwmQYHVP4S1xzk7GHF5lrAeg06sH6V/jD/6KLNYeJoIGrH5WxriVrsKxTODprYV66E4pCtM/XgKCtv0SmagrkjuKrSbC5zh940CqBV2jtB3PP2OJWUVBY1SNgmzIbwGKJidlRWGriXE5Ul10kh7yN1tUjMAQ4owNztrQq/y/Q71o6JvugVYcKxWdkg8nill7drcNvwv+tsN+PyzfWNyhDhPXHvAri9nUgV9A1YQLCHk9id05x0y6FVDzv3XqnUpXK+pZYE2U/c0Z5aKXPydLhPcdq5Uy/DS9Sv7WcxrfVgho9IMHXZHiZh/M9YKbOOmPGCnJRGELEFqYSwTtevDv3ISdIial1jpCYDM2wXXf6B/W+C1u/cspQuITThjKRBgddCHHml+WnxiZsyZwmshL5PvcbAwKfgw/Ge00pYfdo8Vj6ZmDdxurZ2lxAphQSJ/56EC90zB9b190aHZcj28d2OcZZ5LbdgFMxc0cVavPvcOHFJPr7g49nMEm0uahaV55e+FtBR85JZcEkzWE104lpXgo6RyC/RoZURwLylAcg=
  app: turing-feedback-loop